import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CssBaseline, Container } from "@mui/material"
import Header from "./components/header";
import Providers from "./providers";
import authenticated from "./auth/authenticated";
import logout from "./auth/logout";
import { notoSerif } from "./constants/fonts";
import Footer from "./components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shoppy App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = await authenticated();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${notoSerif.variable} antialiased min-h-screen flex flex-col`}>
        <Providers authenticated={isAuthenticated}>
            <CssBaseline />
            <Header logout={logout} />
            <Container className={`${isAuthenticated ? "mt-10" : ""} flex-grow`}>
              {children}
            </Container>
            <Footer />
        </Providers>
      </body>
    </html>
  );
}